/**
 * Environment Configuration Example
 * Rename this file to env-config.js and fill in your actual API keys.
 * DO NOT commit the actual env-config.js file to version control.
 */
window.ENV = {
    VITE_FIREBASE_API_KEY: 'YOUR_FIREBASE_API_KEY',
    VITE_FIREBASE_AUTH_DOMAIN: 'YOUR_FIREBASE_AUTH_DOMAIN',
    VITE_FIREBASE_DATABASE_URL: 'YOUR_FIREBASE_DATABASE_URL',
    VITE_FIREBASE_PROJECT_ID: 'YOUR_FIREBASE_PROJECT_ID',
    VITE_FIREBASE_STORAGE_BUCKET: 'YOUR_FIREBASE_STORAGE_BUCKET',
    VITE_FIREBASE_MESSAGING_SENDER_ID: 'YOUR_FIREBASE_MESSAGING_SENDER_ID',
    VITE_FIREBASE_APP_ID: 'YOUR_FIREBASE_APP_ID',
    VITE_FIREBASE_MEASUREMENT_ID: 'YOUR_FIREBASE_MEASUREMENT_ID',
    VITE_SERP_API_KEY: 'YOUR_SERP_API_KEY',
    VITE_GEMINI_API_KEY_1: 'YOUR_GEMINI_API_KEY_1',
    VITE_GEMINI_API_KEY_2: 'YOUR_GEMINI_API_KEY_2',
    VITE_GEMINI_API_KEY_3: 'YOUR_GEMINI_API_KEY_3',
    VITE_GEMINI_API_KEY_4: 'YOUR_GEMINI_API_KEY_4'
};

console.log('🌍 Environment variables loaded locally');
